version: '3.8'

services:
  neo4j:
    image: neo4j:5.24.2-community
    container_name: neo4j-llm-final-project
    restart: always
    ports:
      - "7474:7474"  # HTTP browser
      - "7687:7687"  # Bolt protocol
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/your_password
      - NEO4JLABS_PLUGINS=["apoc", "bloom"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,bloom.*
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_connector_bolt_listen__address=0.0.0.0:7687
      - NEO4J_dbms_memory_pagecache_size=512M
      - server.config.strict_validation.enabled=false  # Disable strict validation if needed

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
